### ISSUE TITLE
Font 'fontawesome-webfont-v470.ttf' not properly registered.

### ISSUE THREAD

**Issue by aleaho** [Bearded-Hen/Android-Bootstrap#206]
I'm a new fontawesome .I use the fontawesome follow the README.
     The android studio tell me "Font 'fontawesome-webfont-v470.ttf' not properly registered,please see the README at https://github.com/Bearded-Hen/Android-Bootstrap" when I use the "AwesomeTextView".
    I added the "fontawesome-webfont-v470.ttf" to my project in "main/assets". My android version is KitKat (4.4).
   The error infomation is :

08-09 17:26:29.236 16764-16764/com.aleaho.layouttest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.aleaho.layouttest, PID: 16764
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aleaho.layouttest/com.aleaho.layouttest.MainActivity}: android.view.InflateException: Binary XML file line #33: Error inflating class com.beardedhen.androidbootstrap.AwesomeTextView
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2366)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                           at android.os.Looper.loop(Looper.java:193)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5328)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class com.beardedhen.androidbootstrap.AwesomeTextView
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                           at com.aleaho.layouttest.MainActivity.onCreate(MainActivity.java:11)
                                                                           at android.app.Activity.performCreate(Activity.java:5354)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                           at android.os.Looper.loop(Looper.java:193) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5328) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                           at com.aleaho.layouttest.MainActivity.onCreate(MainActivity.java:11) 
                                                                           at android.app.Activity.performCreate(Activity.java:5354) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                           at android.os.Looper.loop(Looper.java:193) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5328) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: java.lang.RuntimeException: Font 'fontawesome-webfont-v470.ttf' not properly registered, please see the README at https://github.com/Bearded-Hen/Android-Bootstrap
                                                                           at com.beardedhen.androidbootstrap.TypefaceProvider.retrieveRegisteredIconSet(TypefaceProvider.java:75)
                                                                           at com.beardedhen.androidbootstrap.AwesomeTextView.initialise(AwesomeTextView.java:100)
                                                                           at com.beardedhen.androidbootstrap.AwesomeTextView.<init>(AwesomeTextView.java:69)
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                           at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                           at com.aleaho.layouttest.MainActivity.onCreate(MainActivity.java:11) 
                                                                           at android.app.Activity.performCreate(Activity.java:5354) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                           at android.os.Looper.loop(Looper.java:193) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5328) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 

    Help me pelease.

**Comment by renierdbruyn** [comment]
what was the solution?

**Comment by Akwarski** [comment]
add this:
TypefaceProvider.registerDefaultIconSets()
in onCreate before:
setContentView(...)

**Comment by Akwarski** [comment]
> what was the solution?

add this:
TypefaceProvider.registerDefaultIconSets()
in onCreate before:
setContentView(...)
